name: release
on:
    push:
        tags: ["v*"]
permissions:
    id-token: write # for npm provenance
    contents: read
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/
                  scope: "@seatkit"
            - run: npm i -g npm@latest
            - run: npm ci
            - run: npm publish --workspaces --access public
